baseURL: "http://romainmellaza.fr/"
languageCode: fr-fr
title: Romain Mellaza
theme: hugo-theme-itheme
params:
  defaultCover: 'img/code_cover.jpg'
  email: romain.mellaza@orange.fr
  socialMedia:
    - name: Github
      url: https://github.com/4strium
    - name : LinkedIn
      url: https://www.linkedin.com/in/romain-mellaza/
    - name: Twitter
      url: https://twitter.com/RomainMza
    - name : Instagram
      url: https://www.instagram.com/ads.bzh/
  blogroll:
    - name: Collège CROAS AR PENNOC, Guilers(29)
      url: https://www.college-croasarpennoc-guilers.ac-rennes.fr/
    - name: Lycée VAUBAN, Brest(29)
      url: https://www.lycee-vauban-brest.ac-rennes.fr/
