baseURL: "http://mellaza.tech/"
languageCode: fr-fr
title: Romain Mellaza
theme: hugo-theme-itheme
params:
  defaultCover: 'img/cover-images/code_cover.jpg'
  email: 02gpvd9vr@mozmail.com
  socialMedia:
    - name: Github
      url: https://github.com/4strium
    - name : LinkedIn
      url: https://www.linkedin.com/in/romain-mellaza/
    - name: Twitter
      url: https://twitter.com/RomainMza
    - name : Instagram
      url: https://www.instagram.com/ads.bzh/
  blogroll:
    - name: Collège Croas ar Pennoc, Guilers (29)
      url: https://www.college-croasarpennoc-guilers.ac-rennes.fr/
    - name: BAC Général, Lycée Vauban, Brest (29)
      url: https://www.lycee-vauban-brest.ac-rennes.fr/
    - name: CPGE MP2I, Lycée Alain-René Lesage, Vannes (56)
      url: https://lycee-lesage.fr/